# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Plugin Tools Legacy - CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  build:
    name: '${{ matrix.os }}-jdk${{ matrix.java }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' , 'windows-latest' ]
        java: ['11', '17', '21']

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
          distribution: 'temurin'
      - name: Build and Test on ${{ matrix.os }} - ${{ matrix.java }} with WildFly 32.0.0.Final
        # 32.0.0.Final was the first version which deployed channels
        run: mvn clean install '-Dorg.jboss.logmanager.nocolor=true' '-Dversion.org.wildfly=32.0.0.Final'
      - name: Upload surefire logs for failed run
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/'
      - name: Upload failsafe logs for failed run
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failsafe-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/failsafe-reports/'
      - name: Upload logs for failed run
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/*.log'